version: "3.9"

services:
    mysql:
        image: mysql:8.0.27
        platform: linux/amd64
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: password
        restart: always
        networks:
            - mysql-network
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/sql:/docker-entrypoint-initdb.d

    cli:
        image: mysql:8.0.27
        networks:
            - mysql-network
        command: mysql -hmysql -uuser -ppassword db

networks:
    mysql-network:
        driver: bridge
